version: "3.8"

services:
  backend:
    image: part2/example-backend
    build: ../../material-applications/example-backend
    ports:
      - 8080:8080
  frontend:
    image: part2/example-frontend
    build: ../../material-applications/example-frontend
    ports:
      - 5000:5000
