FROM golang:1.16

EXPOSE 8080

WORKDIR /usr/src/app

COPY go.mod go.sum ./

COPY . .

ENV PORT=8080

ENV REQUEST_ORIGIN=http://localhost:5000

RUN useradd -m appuser && chown -R appuser . && go mod download && go mod verify && go build && go clean -modcache && rm -rf *.go *_test.go

USER appuser

CMD [ "./server" ]