FROM node:16-alpine as build-stage

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build

FROM nginx:alpine

EXPOSE 80

COPY --from=build-stage /usr/src/app/build /usr/share/nginx/html