FROM golang:1.16-alpine as build-stage

WORKDIR /usr/src/app

RUN adduser -D appuser && chown -R appuser .

USER appuser

COPY --chown=appuser go.mod go.sum ./

RUN go mod download && go mod verify

COPY --chown=appuser . .

ENV PORT=8080

ENV REQUEST_ORIGIN=http://localhost:5000

RUN CGO_ENABLED=0 go build

FROM scratch

COPY --from=build-stage /usr/src/app/server ./server

EXPOSE 8080

CMD [ "./server" ]