version: "3.8"

services:
  dev_frontend:
    image: example/dev-frontend
    build:
      context: ../../material-applications/example-frontend
      dockerfile: Dockerfile.dev
    command: npm start
    ports:
      - 3000:3000
    volumes:
      - ../../material-applications/example-frontend:/usr/src/app # Let us modify the contents of the container locally
      - node_modules:/usr/src/app/node_modules # A bit of node magic, this ensures the dependencies built for the image are not available locally.
    container_name: example-dev-frontend

volumes: # This is required for the node_modules named volume
  node_modules:
