FROM node:16

EXPOSE 5000

WORKDIR /usr/src/app

COPY . .

# create the appuser
RUN useradd -m appuser

# change the owner of current dir to appuser
RUN chown -R appuser .

RUN npm install -g serve

# now we can change the user
USER appuser

RUN npm install

RUN npm run build

CMD [ "serve", "-s", "-l", "5000", "build" ]